version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - exsilium
  ignore:
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
